name: app
description: "A new events project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  qr_flutter: ^4.1.0 # Ensure you have this version
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  font_awesome_flutter: ^10.1.0
  collection: ^1.18.0
  material_color_utilities: ^0.8.0
  meta: ^1.12.0
  web: ^1.0.0
  cupertino_icons: ^1.0.2
  mobile_scanner: ^3.5.5
  pretty_qr_code: ^2.0.0  # Add this line
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_database: ^10.4.0
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/events.jpeg
    - assets/events1.jpeg
    - assets/banner.jpeg
    - assets/banner1.png
    - assets/image.png
