// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhcZy43SJOG6ClyGafyZMVo62HYPrr1Js',
    appId: '1:289555317356:web:e60016663190e4ddc28e49',
    messagingSenderId: '289555317356',
    projectId: 'eventplus-c70c9',
    authDomain: 'eventplus-c70c9.firebaseapp.com',
    databaseURL: 'https://eventplus-c70c9-default-rtdb.firebaseio.com',
    storageBucket: 'eventplus-c70c9.appspot.com',
    measurementId: 'G-KMWZPS3RE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC20ui7EDGoKmAXLcWqx69zjWMqwfZPZuQ',
    appId: '1:289555317356:android:2eeb8d6ef65827c6c28e49',
    messagingSenderId: '289555317356',
    projectId: 'eventplus-c70c9',
    databaseURL: 'https://eventplus-c70c9-default-rtdb.firebaseio.com',
    storageBucket: 'eventplus-c70c9.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBxwEtGF7qygGxOKmwafxjDwnpsGNWEXbc',
  //   appId: '1:289555317356:ios:432f70955a8b3c6bc28e49',
  //   messagingSenderId: '289555317356',
  //   projectId: 'eventplus-c70c9',
  //   databaseURL: 'https://eventplus-c70c9-default-rtdb.firebaseio.com',
  //   storageBucket: 'eventplus-c70c9.appspot.com',
  //   iosBundleId: 'com.example.app',
  // );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxwEtGF7qygGxOKmwafxjDwnpsGNWEXbc',
    appId: '1:289555317356:ios:432f70955a8b3c6bc28e49',
    messagingSenderId: '289555317356',
    projectId: 'eventplus-c70c9',
    databaseURL: 'https://eventplus-c70c9-default-rtdb.firebaseio.com',
    storageBucket: 'eventplus-c70c9.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhcZy43SJOG6ClyGafyZMVo62HYPrr1Js',
    appId: '1:289555317356:web:e8a83373253b1b42c28e49',
    messagingSenderId: '289555317356',
    projectId: 'eventplus-c70c9',
    authDomain: 'eventplus-c70c9.firebaseapp.com',
    databaseURL: 'https://eventplus-c70c9-default-rtdb.firebaseio.com',
    storageBucket: 'eventplus-c70c9.appspot.com',
    measurementId: 'G-B39V2KDZZT',
  );
}
